# Site settings
title: Thai Pham's Blog
header-img: img/home-bg.jpg
email: thaiphv@gmail.com
description: "This is a place where I keep my notes that I learn on the go as a Web developer"
baseurl: ""
url: ""
twitter_username: thaiphv
github_username:  thaiphv
facebook_username:  thaiphv

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
